version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Singapore"
    groups:
      gha:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Singapore"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "@types/node" # Pinned to current Node version
    groups:
      npm-tools:
        patterns:
          - "*typescript*"
          - "*eslint*"
          - "*prettier*"
        update-types:
          - "minor"
          - "patch"
      npm:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
